### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by BallballTH** [BallballTH/Project-G9#35]

**Comment by BallballTH** [comment]
![1419_20230902231043](https://github.com/BallballTH/Project-G9/assets/49591895/563d5eaf-da70-4441-ba29-53d6c2f5c7dc)
![1419_20230902231048](https://github.com/BallballTH/Project-G9/assets/49591895/4d8ef620-6641-44ac-ba8a-d549cc35e623)
background and pathwalk

**Comment by bbeamuu** [comment]
![image](https://github.com/BallballTH/Project-G9/assets/141818253/1fd7f2d4-bab1-4081-8301-8f20fbbcf281)

**Comment by bbeamuu** [comment]
![image](https://github.com/BallballTH/Project-G9/assets/141818253/d12f582b-0f6f-4209-87c8-041e5e6006c8)
![image](https://github.com/BallballTH/Project-G9/assets/141818253/94812732-7de4-4c66-b66c-1c8e8915ba64)

Pathwalk & bg2
