### ISSUE TITLE
Characters draft

### ISSUE THREAD

**Issue by BallballTH** [BallballTH/Project-G9#4]
ตัวละครแบบคร่าวๆ

**Comment by BallballTH** [comment]
![000](https://github.com/BallballTH/Project-G9/assets/49591895/4f4e7faf-904a-44b2-bbaa-fd4da6f92182)
![001](https://github.com/BallballTH/Project-G9/assets/49591895/85b15cb3-63b6-4a93-a7f4-e80189e4a02a)

**Comment by bbeamuu** [comment]
[Entaneer.zip](https://github.com/BallballTH/Project-G9/files/12528093/Entaneer.zip)

**Comment by bbeamuu** [comment]
[Docccc.zip](https://github.com/BallballTH/Project-G9/files/12593913/Docccc.zip)
doctor
