### ISSUE TITLE
Sounds Effects

### ISSUE THREAD

**Issue by BallballTH** [BallballTH/Project-G9#5]
เสียงต่อย กระโดด คลิ้กเมนู บลาๆ

**Comment by Tawan1101** [comment]
[compressed.zip](https://github.com/BallballTH/Project-G9/files/12518785/compressed.zip)

**Comment by BallballTH** [comment]
> [compressed.zip](https://github.com/BallballTH/Project-G9/files/12518785/compressed.zip)
-กระโดด
-ต่อย1
-ต่อย2
-กระโดด
-block
-เสียงก่อนเริ่มเกม
-เสียงเดินบนน้ำ พื้น 
-โดนต่อย
